# Generated by Django 4.1.6 on 2023-02-10 11:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0002_alter_listofdownloads_file_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listofdownloads",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
