# Generated by Django 4.1.6 on 2023-02-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hello", "0003_alter_listofdownloads_date"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LogMessage",
        ),
    ]
